import * as fs from "node:fs";
import * as path from "node:path";
import { emptySelection, saveSelection } from "@roost/core";

const CHEZMOI_TOML_TMPL = `# chezmoi toml template — generated by roost init
# Uncomment and set your age recipient public key for encrypted files:
# [age]
#   recipient = "age1..."
`;

// Roost's own data lives in the same git repo that doubles as the chezmoi
// source. Without this, chezmoi would treat roost/ (selection.yaml, env.yaml,
// appconfig plists), the per-host state/ dir, and the skills/ backup payload as
// dotfiles to deploy to ~/roost, ~/state, and ~/skills. Tell chezmoi to ignore
// them so they never show up as "managed" or get applied onto a machine.
// (The skills module deploys its own content via symlink/copy into per-IDE dirs,
// NOT via chezmoi apply — so skills/ must be ignored here.)
const CHEZMOI_IGNORE = `# Roost metadata — managed by Roost itself, never deploy as dotfiles.
roost
roost/**
state
state/**
skills
skills/**
`;

export async function runInit(opts: { repoDir: string }): Promise<{ created: string[] }> {
  const { repoDir } = opts;
  const created: string[] = [];

  const roostDir = path.join(repoDir, "roost");
  if (!fs.existsSync(roostDir)) {
    fs.mkdirSync(roostDir, { recursive: true });
    created.push(roostDir);
  }

  const selectionPath = path.join(roostDir, "selection.yaml");
  if (!fs.existsSync(selectionPath)) {
    saveSelection(repoDir, emptySelection());
    created.push(selectionPath);
  }

  const tmplPath = path.join(repoDir, ".chezmoi.toml.tmpl");
  if (!fs.existsSync(tmplPath)) {
    fs.writeFileSync(tmplPath, CHEZMOI_TOML_TMPL, "utf8");
    created.push(tmplPath);
  }

  const ignorePath = path.join(repoDir, ".chezmoiignore");
  if (!fs.existsSync(ignorePath)) {
    fs.writeFileSync(ignorePath, CHEZMOI_IGNORE, "utf8");
    created.push(ignorePath);
  }

  return { created };
}
