import * as fs from "node:fs";
import * as path from "node:path";
import { emptySelection, saveSelection } from "@roost/core";

const CHEZMOI_TOML_TMPL = `# chezmoi toml template — generated by roost init
# Uncomment and set your age recipient public key for encrypted files:
# [age]
#   recipient = "age1..."
`;

export async function runInit(opts: { repoDir: string }): Promise<{ created: string[] }> {
  const { repoDir } = opts;
  const created: string[] = [];

  const roostDir = path.join(repoDir, "roost");
  if (!fs.existsSync(roostDir)) {
    fs.mkdirSync(roostDir, { recursive: true });
    created.push(roostDir);
  }

  const selectionPath = path.join(roostDir, "selection.yaml");
  if (!fs.existsSync(selectionPath)) {
    saveSelection(repoDir, emptySelection());
    created.push(selectionPath);
  }

  const tmplPath = path.join(repoDir, ".chezmoi.toml.tmpl");
  if (!fs.existsSync(tmplPath)) {
    fs.writeFileSync(tmplPath, CHEZMOI_TOML_TMPL, "utf8");
    created.push(tmplPath);
  }

  return { created };
}
